import type { Config } from "tailwindcss";

/**
 * Basket (demo-grocery-web) — "Cold Chain" theme.
 * Generated by the demo-builder Design phase from specs/design-tokens.json.
 *
 * The SEMANTIC NAMES here are the reusable contract (bg-primary, text-heading,
 * font-heading, max-w-page, shadow-md, …): the plumbing components
 * (ConsentManager, DemoFooter, SignalsInspector, InterventionBanner) style
 * against these names. Keys are fixed; only values change per demo.
 *
 * This is a LIGHT theme — the skeleton ships dark, so globals.css and
 * layout.tsx were updated to match (color-scheme: light, new font variables).
 *
 * Tailwind v4 note: bridged in via `@config "../../tailwind.config.ts"` from
 * globals.css.
 */
const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#0C0E0D",
        secondary: "#1B6B47",
        accent: "#1B6B47",
        highlight: "#D9F154",
        background: "#FFFFFF",
        surface: "#F4F6F5",
        "surface-raised": "#FFFFFF",
        border: "#E3E7E5",
        "border-strong": "#D5DAD8",
        light: {
          bg: "#FFFFFF",
          surface: "#F4F6F5",
          border: "#E3E7E5",
        },
        heading: "#0C0E0D",
        body: "#5B6260",
        muted: "#8A918E",
        inverse: "#FFFFFF",
        link: "#1B6B47",
        success: "#1B6B47",
        warning: "#B8761B",
        error: "#C0392B",
        info: "#1D5FA8",
      },
      fontFamily: {
        heading: ["var(--font-heading)", "ui-sans-serif", "system-ui", "sans-serif"],
        body: ["var(--font-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "ui-monospace", "monospace"],
      },
      fontSize: {
        display: ["3rem", { lineHeight: "1.06", letterSpacing: "-0.04em" }],
        h1: ["2.5rem", { lineHeight: "1.1", letterSpacing: "-0.035em" }],
        h2: ["1.875rem", { lineHeight: "1.14", letterSpacing: "-0.03em" }],
        h3: ["1.375rem", { lineHeight: "1.2", letterSpacing: "-0.025em" }],
        h4: ["1.0625rem", { lineHeight: "1.28", letterSpacing: "-0.02em" }],
        h5: ["0.9375rem", { lineHeight: "1.35", letterSpacing: "-0.01em" }],
        body: ["0.9375rem", { lineHeight: "1.55" }],
        small: ["0.8125rem", { lineHeight: "1.45" }],
        nav: ["0.8125rem", { lineHeight: "1.2", letterSpacing: "0.01em" }],
      },
      fontWeight: {
        light: "300",
        normal: "400",
        medium: "500",
        semibold: "600",
        bold: "700",
        extrabold: "800",
      },
      spacing: {
        xs: "0.25rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "1.5rem",
        xl: "2.5rem",
        "2xl": "4rem",
        section: "4.5rem",
      },
      maxWidth: {
        // GOTCHA (carried from real builds): the custom `spacing` keys above
        // (sm/md/lg/xl/2xl) outrank theme.maxWidth for `max-w-*` under the
        // @config bridge, collapsing `max-w-md`/`xl`/`2xl` to tiny values. Use
        // an arbitrary value (`max-w-[28rem]`) for small/medium widths; `page`
        // is collision-free.
        page: "1320px",
      },
      borderRadius: {
        sm: "0.125rem",
        md: "0.1875rem",
        lg: "0.375rem",
        full: "9999px",
      },
      boxShadow: {
        sm: "0 1px 2px rgba(12, 14, 13, 0.06)",
        md: "0 4px 14px rgba(12, 14, 13, 0.08)",
        lg: "0 16px 40px rgba(12, 14, 13, 0.12)",
      },
    },
  },
  plugins: [],
};

export default config;
