import { trackSelfDescribingEvent, CommonEventProperties, SelfDescribingJson } from '@snowplow/browser-tracker';
import * as Ecom from '@snowplow/browser-plugin-snowplow-ecommerce';
// Automatically generated by Snowtype

export type InterventionInteraction = {
    /**
     * The Signals intervention name
     */
    name: string;
    /**
     * The interaction type: view, click or dismiss
     */
    type: InterventionInteractionType;
}

/**
 * The interaction type: view, click or dismiss
 */
export type InterventionInteractionType = "view" | "click" | "dismiss";

export type ClassifyIntent = {
    /**
     * End-to-end /api/intent round-trip time in milliseconds, measured in the browser.
     */
    latency_ms?: number | null;
    /**
     * What caused this read: a debounced add to basket, remove from basket or search, or a
     * manual Signals Inspector refresh.
     */
    trigger?: Trigger | null;
}

export type Trigger = "add_to_cart" | "remove_from_cart" | "search" | "inspector";

export type ShopperIntent = {
    /**
     * Raw Noul probability (0-1) that the shopper is budget driven.
     */
    budget_driven_probability?: number | null;
    /**
     * Raw Noul probability (0-1) that the shopper is convenience seeking.
     */
    convenience_seeking_probability?: number | null;
    /**
     * Raw Noul probability (0-1) that the shopper is a foodie explorer.
     */
    foodie_explorer_probability?: number | null;
    /**
     * Raw Noul probability (0-1) that the shopper is health conscious.
     */
    health_conscious_probability?: number | null;
    /**
     * Shopping occasion after code policy. Drives what to show.
     */
    occasion: Occasion;
    /**
     * Jev confidence (0-1) in the occasion choice.
     */
    occasion_confidence?: number | null;
    /**
     * Primary shopper persona after code policy. Drives how to frame messaging.
     */
    persona_primary: PersonaPrimary;
    /**
     * Whether the plant-based filter is active (plant_based_probability >= 0.8).
     */
    plant_based_filter?: boolean | null;
    /**
     * Raw Noul probability (0-1) that the shopper prefers plant-based products.
     */
    plant_based_probability?: number | null;
    /**
     * Journey stage after code policy (overrides and confidence gating). Drives when and how
     * hard to intervene.
     */
    stage: Stage;
    /**
     * Jev confidence (0-1) in the stage choice.
     */
    stage_confidence?: number | null;
    /**
     * Jev's raw stage pick before code override or confidence gating.
     */
    stage_model_choice?: null | string;
}

/**
 * Shopping occasion after code policy. Drives what to show.
 */
export type Occasion = "restock_weekly" | "restock_top_up" | "meal" | "event" | "unclear" | "not_enough_signal";

/**
 * Primary shopper persona after code policy. Drives how to frame messaging.
 */
export type PersonaPrimary = "budget_driven" | "health_conscious" | "convenience_seeking" | "foodie_explorer" | "generalist" | "not_enough_signal";

/**
 * Journey stage after code policy (overrides and confidence gating). Drives when and how
 * hard to intervene.
 */
export type Stage = "browsing" | "on_a_mission" | "comparing" | "ready_to_buy" | "hesitating" | "checking_out" | "purchased" | "not_enough_signal";

/**
 * Captures a search action by the user including the search term and resulting metadata.
 */
export type SearchPerformed = {
    /**
     * The type of search performed, a full search to the results page, or a quick search from
     * the dropdown.
     */
    search_type?: SearchType;
    /**
     * The search term entered by the user.
     */
    term: string;
    /**
     * The total number of results returned for the search.
     */
    total_results?: number | null;
}

/**
 * The type of search performed, a full search to the results page, or a quick search from
 * the dropdown.
 */
export type SearchType = "full" | "quick";

/**
 * Generated from a property rule
 */
export type SnowplowEcommerceActionRemoveFromBasket = {
    name?: null | string;
    type:  SnowplowEcommerceActionRemoveFromBasketType;
    [property: string]: any;
}

export type SnowplowEcommerceActionRemoveFromBasketType = "remove_from_cart";

/**
 * Generated from a property rule
 */
export type SnowplowEcommerceActionViewProduct = {
    name?: null | string;
    type:  SnowplowEcommerceActionViewProductType;
    [property: string]: any;
}

export type SnowplowEcommerceActionViewProductType = "product_view";

/**
 * Context entity describing the agent, its configuration, and current state when performing
 * actions. - Generated from a property rule
 */
export type AgentClassifyShopperIntent = {
    /**
     * Application version
     */
    application_version?: null | string;
    /**
     * Number of messages in conversation history at this point
     */
    conversation_messages_count?: number | null;
    /**
     * Current step number within the invocation
     */
    current_step_number?: number | null;
    /**
     * Unique identifier for current agent invocation
     */
    invocation_id: string;
    /**
     * LLM model identifier (e.g., claude-sonnet-4-20250514)
     */
    model_name: string;
    /**
     * LLM provider (e.g., anthropic, openai)
     */
    model_provider: string;
    /**
     * Always intent_classifier for this event spec.
     */
    type: AgentClassifyShopperIntentType;
}

/**
 * Always intent_classifier for this event spec.
 */
export type AgentClassifyShopperIntentType = "intent_classifier";

/**
 * Generated from a property rule
 */
export type SnowplowEcommerceActionProgressCheckoutStep = {
    name?: null | string;
    type:  SnowplowEcommerceActionProgressCheckoutStepType;
    [property: string]: any;
}

export type SnowplowEcommerceActionProgressCheckoutStepType = "checkout_step";

/**
 * Generated from a property rule
 */
export type SnowplowEcommerceActionAddToBasket = {
    name?: null | string;
    type:  SnowplowEcommerceActionAddToBasketType;
    [property: string]: any;
}

export type SnowplowEcommerceActionAddToBasketType = "add_to_cart";

/**
 * Generated from a property rule
 */
export type SnowplowEcommerceActionCompleteTransaction = {
    name?: null | string;
    type:  SnowplowEcommerceActionCompleteTransactionType;
    [property: string]: any;
}

export type SnowplowEcommerceActionCompleteTransactionType = "transaction";

/**
 * Creates a Snowplow Event Specification entity.
 */
export function createEventSpecification(eventSpecification: Omit<EventSpecification, 'data_product_domain'> & Partial<Pick<EventSpecification, 'data_product_domain'>>){
    return {
        schema:
            'iglu:com.snowplowanalytics.snowplow/event_specification/jsonschema/1-0-4',
        data: eventSpecification,
    }
}

/**
 * Automatically attached context for event specifications
 */
interface EventSpecification {
    id: string;
    version: number;
    name: string;
    data_product_id: string;
    data_product_name: string;
    data_product_domain?: string;
}

type ContextsOrTimestamp<T = any> = Omit<CommonEventProperties<T>, 'context'> & { context?: SelfDescribingJson<T>[] | null | undefined }
/**
 * Track a Snowplow event for InterventionInteraction.
 * 
 */
export function trackInterventionInteraction<T extends {} = any>(interventionInteraction: InterventionInteraction & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = interventionInteraction;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.demo/intervention_interaction/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow InterventionInteraction entity.
 */
export function createInterventionInteraction(interventionInteraction: InterventionInteraction){
    return {
        schema: 'iglu:com.demo/intervention_interaction/jsonschema/1-0-0',
        data: interventionInteraction
    }
}
/**
 * Track a Snowplow event for ClassifyIntent.
 * 
 */
export function trackClassifyIntent<T extends {} = any>(classifyIntent: ClassifyIntent & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = classifyIntent;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.demo/classify_intent/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow ClassifyIntent entity.
 */
export function createClassifyIntent(classifyIntent: ClassifyIntent){
    return {
        schema: 'iglu:com.demo/classify_intent/jsonschema/1-0-0',
        data: classifyIntent
    }
}
/**
 * Track a Snowplow event for ShopperIntent.
 * 
 */
export function trackShopperIntent<T extends {} = any>(shopperIntent: ShopperIntent & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = shopperIntent;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.demo/shopper_intent/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow ShopperIntent entity.
 */
export function createShopperIntent(shopperIntent: ShopperIntent){
    return {
        schema: 'iglu:com.demo/shopper_intent/jsonschema/1-0-0',
        data: shopperIntent
    }
}
/**
 * Track a Snowplow event for SearchPerformed.
 * Captures a search action by the user including the search term and resulting metadata.
 */
export function trackSearchPerformed<T extends {} = any>(searchPerformed: SearchPerformed & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = searchPerformed;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.demo/search_performed/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow SearchPerformed entity.
 */
export function createSearchPerformed(searchPerformed: SearchPerformed){
    return {
        schema: 'iglu:com.demo/search_performed/jsonschema/1-0-0',
        data: searchPerformed
    }
}
/**
 * Track a Snowplow event for SnowplowEcommerceActionRemoveFromBasket.
 * Generated from a property rule
 */
function trackSnowplowEcommerceActionRemoveFromBasket<T extends {} = any>(snowplowEcommerceActionRemoveFromBasket: SnowplowEcommerceActionRemoveFromBasket & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = snowplowEcommerceActionRemoveFromBasket;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.snowplowanalytics.snowplow.ecommerce/snowplow_ecommerce_action/jsonschema/1-0-2',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Track a Snowplow event for SnowplowEcommerceActionViewProduct.
 * Generated from a property rule
 */
function trackSnowplowEcommerceActionViewProduct<T extends {} = any>(snowplowEcommerceActionViewProduct: SnowplowEcommerceActionViewProduct & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = snowplowEcommerceActionViewProduct;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.snowplowanalytics.snowplow.ecommerce/snowplow_ecommerce_action/jsonschema/1-0-2',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow AgentClassifyShopperIntent entity.
 */
export function createAgentClassifyShopperIntent(agentClassifyShopperIntent: AgentClassifyShopperIntent){
    return {
        schema: 'iglu:com.demo/agent/jsonschema/1-0-0',
        data: agentClassifyShopperIntent
    }
}
/**
 * Track a Snowplow event for SnowplowEcommerceActionProgressCheckoutStep.
 * Generated from a property rule
 */
function trackSnowplowEcommerceActionProgressCheckoutStep<T extends {} = any>(snowplowEcommerceActionProgressCheckoutStep: SnowplowEcommerceActionProgressCheckoutStep & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = snowplowEcommerceActionProgressCheckoutStep;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.snowplowanalytics.snowplow.ecommerce/snowplow_ecommerce_action/jsonschema/1-0-2',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Track a Snowplow event for SnowplowEcommerceActionAddToBasket.
 * Generated from a property rule
 */
function trackSnowplowEcommerceActionAddToBasket<T extends {} = any>(snowplowEcommerceActionAddToBasket: SnowplowEcommerceActionAddToBasket & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = snowplowEcommerceActionAddToBasket;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.snowplowanalytics.snowplow.ecommerce/snowplow_ecommerce_action/jsonschema/1-0-2',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Track a Snowplow event for SnowplowEcommerceActionCompleteTransaction.
 * Generated from a property rule
 */
function trackSnowplowEcommerceActionCompleteTransaction<T extends {} = any>(snowplowEcommerceActionCompleteTransaction: SnowplowEcommerceActionCompleteTransaction & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = snowplowEcommerceActionCompleteTransaction;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.snowplowanalytics.snowplow.ecommerce/snowplow_ecommerce_action/jsonschema/1-0-2',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}


/**
 * Tracks a ClassifyShopperIntent event specification.
 * ID: 1cd8daca-5f4e-4ba2-8f7d-eaa51cfed2fb
 */
export function trackClassifyShopperIntentSpec(classifyShopperIntent: ClassifyIntent & ContextsOrTimestamp<ShopperIntent | AgentClassifyShopperIntent>, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: '1cd8daca-5f4e-4ba2-8f7d-eaa51cfed2fb',
        version: 0,
        name: 'Classify Shopper Intent',
        data_product_id: '9e64295e-1e49-40d3-81b3-71a9b1873e84',
        data_product_name: 'Grocery Shopping Journey',
        data_product_domain: 'Product'
    });

    const context = Array.isArray(classifyShopperIntent.context)
        ? [...classifyShopperIntent.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedClassifyShopperIntent = {
        ...classifyShopperIntent,
        context,
    };

    trackClassifyIntent<ShopperIntent | AgentClassifyShopperIntent | EventSpecification>(modifiedClassifyShopperIntent, trackers);
}
/**
 * Tracks a PerformSearch event specification.
 * ID: cb1e0fe4-d89b-4d80-abe0-83ca57949b30
 */
export function trackPerformSearchSpec(performSearch: SearchPerformed & ContextsOrTimestamp, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: 'cb1e0fe4-d89b-4d80-abe0-83ca57949b30',
        version: 0,
        name: 'Perform Search',
        data_product_id: '9e64295e-1e49-40d3-81b3-71a9b1873e84',
        data_product_name: 'Grocery Shopping Journey',
        data_product_domain: 'Product'
    });

    const context = Array.isArray(performSearch.context)
        ? [...performSearch.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedPerformSearch = {
        ...performSearch,
        context,
    };

    trackSearchPerformed<Record<string, unknown> | EventSpecification>(modifiedPerformSearch, trackers);
}

/**
 * @deprecated Outdated data structure detected.
 * Tracks a RemoveFromBasket event specification.
 * ID: 059669a8-d667-4603-bd83-710994167c66
 */
export function trackRemoveFromBasketSpec(removeFromBasket: Ecom.Cart & Ecom.CommonEcommerceEventProperties, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: '059669a8-d667-4603-bd83-710994167c66',
        version: 0,
        name: 'Remove From Basket',
        data_product_id: '9e64295e-1e49-40d3-81b3-71a9b1873e84',
        data_product_name: 'Grocery Shopping Journey',
        data_product_domain: 'Product'
    });

    const context = Array.isArray(removeFromBasket.context)
        ? [...removeFromBasket.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedRemoveFromBasket = {
        ...removeFromBasket,
        context: context as unknown as SelfDescribingJson<Record<string, unknown>>[],
    };

    Ecom.trackRemoveFromCart(modifiedRemoveFromBasket, trackers);
}
/**
 * @deprecated Outdated data structure detected.
 * Tracks a ViewProduct event specification.
 * ID: 16d74354-595f-4935-8423-fabf7bdd5be1
 */
export function trackViewProductSpec(viewProduct: Ecom.Product & Ecom.CommonEcommerceEventProperties, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: '16d74354-595f-4935-8423-fabf7bdd5be1',
        version: 0,
        name: 'View Product',
        data_product_id: '9e64295e-1e49-40d3-81b3-71a9b1873e84',
        data_product_name: 'Grocery Shopping Journey',
        data_product_domain: 'Product'
    });

    const context = Array.isArray(viewProduct.context)
        ? [...viewProduct.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedViewProduct = {
        ...viewProduct,
        context: context as unknown as SelfDescribingJson<Record<string, unknown>>[],
    };

    Ecom.trackProductView(modifiedViewProduct, trackers);
}
/**
 * @deprecated Outdated data structure detected.
 * Tracks a ProgressCheckoutStep event specification.
 * ID: 3e6d45e9-ce73-48ff-9fa8-7d1b69726f8a
 */
export function trackProgressCheckoutStepSpec(progressCheckoutStep: Ecom.CheckoutStep & Ecom.CommonEcommerceEventProperties, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: '3e6d45e9-ce73-48ff-9fa8-7d1b69726f8a',
        version: 0,
        name: 'Progress Checkout Step',
        data_product_id: '9e64295e-1e49-40d3-81b3-71a9b1873e84',
        data_product_name: 'Grocery Shopping Journey',
        data_product_domain: 'Product'
    });

    const context = Array.isArray(progressCheckoutStep.context)
        ? [...progressCheckoutStep.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedProgressCheckoutStep = {
        ...progressCheckoutStep,
        context: context as unknown as SelfDescribingJson<Record<string, unknown>>[],
    };

    Ecom.trackCheckoutStep(modifiedProgressCheckoutStep, trackers);
}
/**
 * @deprecated Outdated data structure detected.
 * Tracks a AddToBasket event specification.
 * ID: 9d06f6e1-b7e5-4f91-9383-de947a156f7d
 */
export function trackAddToBasketSpec(addToBasket: Ecom.Cart & Ecom.CommonEcommerceEventProperties, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: '9d06f6e1-b7e5-4f91-9383-de947a156f7d',
        version: 0,
        name: 'Add To Basket',
        data_product_id: '9e64295e-1e49-40d3-81b3-71a9b1873e84',
        data_product_name: 'Grocery Shopping Journey',
        data_product_domain: 'Product'
    });

    const context = Array.isArray(addToBasket.context)
        ? [...addToBasket.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedAddToBasket = {
        ...addToBasket,
        context: context as unknown as SelfDescribingJson<Record<string, unknown>>[],
    };

    Ecom.trackAddToCart(modifiedAddToBasket, trackers);
}
/**
 * @deprecated Outdated data structure detected.
 * Tracks a CompleteTransaction event specification.
 * ID: a299714a-1bb7-4e20-92ce-4cd2ee454074
 */
export function trackCompleteTransactionSpec(completeTransaction: Ecom.SPTransaction & Ecom.CommonEcommerceEventProperties, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: 'a299714a-1bb7-4e20-92ce-4cd2ee454074',
        version: 0,
        name: 'Complete Transaction',
        data_product_id: '9e64295e-1e49-40d3-81b3-71a9b1873e84',
        data_product_name: 'Grocery Shopping Journey',
        data_product_domain: 'Product'
    });

    const context = Array.isArray(completeTransaction.context)
        ? [...completeTransaction.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedCompleteTransaction = {
        ...completeTransaction,
        context: context as unknown as SelfDescribingJson<Record<string, unknown>>[],
    };

    Ecom.trackTransaction(modifiedCompleteTransaction, trackers);
}

